[package]
name = "debug-ui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ui = { path = "../ui"}
graphics = { path = "../graphics"}
egui= { version = "0.14.0" }
egui_glium= { version = "0.14.0" }